[build]
target = "thumbv7m-none-eabi"

[target.thumbv7m-none-eabi]
runner = "qemu-system-arm -cpu cortex-m3 -machine lm3s6965evb -nographic -semihosting -kernel"

[target.thumbv7m-none-eabi.dev-profile]
opt-level = "s"

[target.thumbv7m-none-eabi.release-profile]
opt-level = "z"
